<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2013 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

 echo "<h1>User Information</h1>\n";
 echo "<p><strong>Username: </strong>" . $this->username . "</p>\n";
 echo "<p><strong>First Name: </strong>" . $this->user_details['first_name'] . "</p>\n";
 echo "<p><strong>Last Name: </strong>" . $this->user_details['last_name'] . "</p>\n";

 if( array_key_exists("groups", $this->user_details) && is_array($this->user_details['groups']) && sizeof($this->user_details['groups']) > 0 ) {
	 echo "<p><strong>Group Membership</strong></p><ul>";
	 foreach( $this->user_details['groups'] as $group_membership ) {
		 echo "<li>" . $group_membership . "</li>";
	 }
	 echo "</ul>";
 }

?>