<form action="" method="POST">
	<p>Please Login to the <?php echo QUIZ_SYSTEM_NAME; ?> using your username and password</p>
	<table id="logintable">
		<tr>
			<td><strong>Username</strong></td>
			<td><input type="text" name="rqz-username" /></td>
		</tr>
		<tr>
			<td><strong>Password</strong></td>
			<td><input type="password" name="rqz-password" /></td>
		</tr>
	</table>
	<input type="submit" value="Login" />
</form>