<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?><h1>Pass / Fail Results</h1>
<form action="" method="post">
	<select name="group">
<?php
	foreach( $this->all_groups as $group ) {
		if( $this->group == $group ) {
			echo "<option selected='selected'>" . $group . "</option>\n";
		}else{
			echo "<option>" . $group . "</option>\n";
		}
	}
?>
	</select>
	<input type="submit" value="Change" />
</form>


<?php
if( is_null($this->group) ):
?>
	<p>Please Select a Group</p>
<?php
else:

	// Sort the members by last name
	usort($this->members, array("View_Helper_Sort", "sort_by_last_name"));


	// Header
	echo "<div style='height:30px'></div>\n";
	echo "<table><tr><td></td>";
	foreach( $this->quizzes as $quiz ) {
		echo "<th>" . $quiz->getName() . "</th>";
	}
	echo "</tr>\n";
	
	// Each Row contains a student, then the results they got for each quiz
	foreach( $this->members as $member ) {
		echo "<tr>\n";
		echo "<th>" . $member['last_name'] . " " . $member['first_name'] . "</th>";
		
		foreach( $this->quizzes as $quiz ) {
			echo "<td>" . $this->quiz_results[ $quiz->getID() ][ $member['username'] ] . "</td>\n";
		}
		
		echo "</tr>\n";
	}
	
	
	echo "</table>\n";


endif;
?>