<h2>List of Quizzes currently in the system</h2>
<p>Click on the corresponding <img src='<?php echo $this->baseUrl; ?>/images/edit_small.png' /> to edit a quiz.<br/>
Click on the corresponding <img src='<?php echo $this->baseUrl; ?>/images/delete_small.png' /> to delete a quiz.<br/>
Click on the quiz <em>name</em> to view/edit the concepts it tests.
</p>

<table>
	<tr>
		<th>Quiz Name</th>
		<th>Quiz Group</th>
		<th>Opens on</th>
		<th>Closes On</th>
		<th>Max Attempts</th>
		<th>Pass Mark</th>
		<th>Actions</th>
	</tr>
<?php
	$vQuizzes = $this->quizzes;
	foreach($vQuizzes as $vQuiz){
		echo "\t<tr>\n";
		echo "\t\t<td><a class='thickbox' href='". $this->url(array("controller"=>"admin", "action"=>"showconcepts")) ."?id=".$vQuiz->getID()."'>".$vQuiz->getQuiz_name()."</a></td>\n";
		echo "\t\t<td>".$vQuiz->getPermissions_group()."</td>\n";
		echo "\t\t<td>".date(DEFAULT_DATE_FORMAT,$vQuiz->getOpen_date())."</td>\n";
		echo "\t\t<td>".date(DEFAULT_DATE_FORMAT,$vQuiz->getClose_date())."</td>\n";
		echo "\t\t<td>".$vQuiz->getMax_attempts()."</td>\n";
		echo "\t\t<td>".$vQuiz->getPercentage_pass()."</td>\n";
		echo "\t\t<td><a href='". $this->url(array("controller" => "admin", "action" => "addedit"))  . "?id=".$vQuiz->getID()."'><img src='". $this->baseUrl ."/images/edit_small.png'/></a> 
						<a href='". $this->url(array("controller" => "admin", "action" => "deletequiz")) ."?id=".$vQuiz->getID()."' onClick='var answer=confirm(\"Are you sure you want to delete this quiz? All associated results will also be deleted.\"); if(!answer){ return false; }'><img src='". $this->baseUrl ."/images/delete_small.png'/></a></td>\n";
		echo "\t</tr>\n";
	}

?>	
</table>

<img src="<?php echo $this->baseUrl; ?>/images/add_16.png" /> <a href="<?php echo $this->url(array("controller" => "admin", "action" => "addedit")) ?>">Add new Quiz</a>