<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?><h2>XML Import</h2>
<?php
if( isset($this->count) ):
?>
<p>This section allows you to import the XML files in the <em>Questions</em> directory on the
server into the database</p>

<p><strong>Warning:</strong> References to existing XML files will not be deleted. If you have removed any XML files from the questions folder, remove them from the Question_Base table in the database.</p>
<p>Number of Files currently in the <em>Questions</em> directory:
<?php
	echo $this->count;
?> 
</p>
<form action="" method="post">
	<input type="hidden" name="process" value="1" />
	<input type="submit" value="Process" />
</form>
<?php
endif;
?>