<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
?><h1>Quiz Results</h1>
<p>Click on a Quiz to see its results</p>

<table>
	<tr>
		<th>Quiz Name</th>
		<th>Total Number Of Attempts</th>
		<th>Date Due</th>
	</tr>
<?php
	foreach( $this->quizzes as $quiz ) {
		$attempts = $quiz->getQuizAttempts();
		$end_date = $quiz->getClose_date();
		
		echo "<tr>\n";
				
		echo "<td><a href='". $this->url( array("controller" => "admin", "action" => "resultsquiz", "quiz_id" => $quiz->getID()) ) ."'>" . $quiz->getName() . "</a></td>\n";
		echo "<td>" . sizeof($attempts) . "</td>\n";
		echo "<td>" . date(DEFAULT_DATE_FORMAT, $end_date) . "</td>\n";
		
		echo "</tr>\n";	
	}
?>
</table>