<?php
/**
 *  Randomised Programming Quiz System - A quiz system that develops random programming questions from defined templates
 *  Copyright (C) 2010-2012 Ben Evans <ben@nebev.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/
	$vQuiz = $this->quiz;
?>

<h2>Quiz Concepts</h2>
<h3><?php echo $vQuiz->getQuiz_name(); ?></h3>
<p>The concepts and difficulties being assessed in this quiz are listed below:</p>
<table>
	<tr>
		<th>Num of Questions</th>
		<th>Concept</th>
		<th>Difficulty (from)</th>
		<th>Difficulty (to)</th>
		<th>Actions</th>
	</tr>
	
<?php

/*	Display each Quiz Concept in a table */
	$vTestedConcepts = $vQuiz->getTestedConcepts();

	
	foreach($vTestedConcepts as $vTestedConcept){
		echo "\t<tr>\n";
		echo "\t\t<td>".$vTestedConcept->getNumber_tested()."</td>\n";
		echo "\t\t<td>".$vTestedConcept->getConcept()->getConcept_name()."</td>\n";
		echo "\t\t<td>".$vTestedConcept->getLower_difficulty()."</td>\n";
		echo "\t\t<td>".$vTestedConcept->getHigher_difficulty()."</td>\n";
		echo "\t\t<td><a href='". $this->url(array("controller" => "admin", "action" => "addconcept", "tested_concept" => $vTestedConcept->getID())) ."'><img src='". $this->baseUrl ."/images/edit_small.png' /</a> <a href='". $this->url(array("controller" => "admin", "action" => "deleteconcept")) ."?concept_id=".$vTestedConcept->getID() ."' onclick='var ans=confirm(\"Are you sure you want to delete this concept from this quiz?\"); if(!ans){return false;}'><img src='". $this->baseUrl ."/images/delete_small.png' /></a></td>\n";
		echo "\t</tr>\n";
	}

?>
</table>

<a href="<?php echo $this->url( array("controller" => "admin", "action" => "addconcept", "quiz_id" => $vQuiz->getID()) ); ?>">Add a Tested Concept to this Quiz</a>

</div>